### ISSUE TITLE
segmentation fault when sending notice

### ISSUE THREAD

**Issue by mattias-lundell** [airbrake/gobrake#350]
Got this earlier today (sorry for the format):
```
"Failed to send error to Airbrake: Post "https://api.airbrake.io/api/v3/projects/XXXXX/notices": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\n "
"\t/code/vendor/github.com/airbrake/gobrake/v5/notifier.go:358 +0x11e\n "
"created by github.com/airbrake/gobrake/v5.(*Notifier).SendNoticeAsync\n "
"\t/code/vendor/github.com/airbrake/gobrake/v5/notifier.go:361 +0x47\n "
"github.com/airbrake/gobrake/v5.(*Notifier).SendNoticeAsync.func1()\n "
"\t/code/vendor/github.com/airbrake/gobrake/v5/notifier.go:334 +0xb48\n "
"github.com/airbrake/gobrake/v5.(*Notifier).sendNotice(0xc0005387e0, 0xdc87e4?)\n "
"\t/code/vendor/github.com/airbrake/gobrake/v5/backlog.go:73 +0x168\n "
"github.com/airbrake/gobrake/v5.setNoticeBacklog(0xc072ba8db0?)\n "
"\t/code/vendor/github.com/airbrake/gobrake/v5/backlog.go:102 +0x5e1\n "
"github.com/airbrake/gobrake/v5.(*noticeBacklog).flushNoticeBacklog(0xc0002bfd10)\n "
"goroutine 14458432 [running]:\n "
"\n "
"[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x74af01]\n "
"panic: runtime error: invalid memory address or nil pointer dereference\n "
"gobrake: 2022/12/21 14:55:31 backlog.go:100: Backlog notice failed = Post "https://api.airbrake.io/api/v3/projects/XXXXX/notices": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\n "
```

Looking at code one should probably be a bit more defensive when attempting to close the response body.

```
// flushNoticeBacklog sends the backlog notice after the backlog period is over.
func (nb *noticeBacklog) flushNoticeBacklog() {
	buf := buffers.Get().(*bytes.Buffer)
	for _, notice := range nb.notices {
		err := json.NewEncoder(buf).Encode(notice)
		if err != nil {
			logger.Printf("Backlog notice failed = %s", err)
		}
		req, err := http.NewRequest(
			http.MethodPost,
			fmt.Sprintf("%s/api/v3/projects/%d/notices",
				nb.opt.Host, nb.opt.ProjectId),
			buf,
		)
		if err != nil {
			logger.Printf("Backlog notice failed = %s", err)
		}

		req.Header.Set("Authorization", "Bearer "+nb.opt.ProjectKey)
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("User-Agent", userAgent)
		resp, err := nb.opt.HTTPClient.Do(req)
		if err != nil {
			logger.Printf("Backlog notice failed = %s", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode > 400 {
			logger.Printf("Backlog notice failed = %q", resp.Status)
		}
		buf.Reset()
	}
	nb.notices = nil
}
```

some days ago got the same error but when attempting to send some route metrics

```
2022-11-05 21:32:43.878	"\t/usr/local/go/src/time/sleep.go:176 +0x32\n "
2022-11-05 21:32:43.878	"created by time.goFunc\n "
2022-11-05 21:32:43.878	"\t/code/vendor/github.com/airbrake/gobrake/v5/route_breakdown.go:66 +0xfd\n "
2022-11-05 21:32:43.878	"github.com/airbrake/gobrake/v5.(*routeBreakdowns).Flush(0xc000b17080)\n "
2022-11-05 21:32:43.878	"\t/code/vendor/github.com/airbrake/gobrake/v5/route_breakdown.go:142 +0xa47\n "
2022-11-05 21:32:43.878	"github.com/airbrake/gobrake/v5.(*routeBreakdowns).send(0xc000b17080, 0xc10aa987b8?)\n "
2022-11-05 21:32:43.878	"\t/code/vendor/github.com/airbrake/gobrake/v5/backlog.go:172 +0x151\n "
2022-11-05 21:32:43.878	"github.com/airbrake/gobrake/v5.setRouteBreakdownBacklog({{0xc000042765, 0x12}, {0xc0f15781b8, 0x1, 0x1}})\n "
2022-11-05 21:32:43.877	"\t/code/vendor/github.com/airbrake/gobrake/v5/backlog.go:201 +0x5cd\n "
2022-11-05 21:32:43.877	"github.com/airbrake/gobrake/v5.(*apmBacklog).flushRouteBreakdownBacklog(0xc0001ea9a0)\n "
2022-11-05 21:32:43.877	"goroutine 11646332 [running]:\n "
2022-11-05 21:32:43.877	"\n "
2022-11-05 21:32:43.877	"[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x77512d]\n "
2022-11-05 21:32:43.877	"panic: runtime error: invalid memory address or nil pointer dereference\n "
2022-11-05 21:32:43.875	"gobrake: 2022/11/05 20:32:43 backlog.go:199: Backlog route stat failed = Put "https://api.airbrake.io/api/v5/projects/xxxxx/routes-breakdowns": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\n "
```

and the problem is the same

```// flushQueueBacklog sends the queue backlog after the backlog period is over.
func (ab *apmBacklog) flushQueueBacklog() {
	buf := buffers.Get().(*bytes.Buffer)
	for _, queue := range ab.queues {
		err := json.NewEncoder(buf).Encode(queue)
		if err != nil {
			logger.Printf("Backlog queue failed = %s", err)
		}
		req, err := http.NewRequest(
			http.MethodPut,
			fmt.Sprintf("%s/api/v5/projects/%d/queues-stats",
				ab.opt.APMHost, ab.opt.ProjectId),
			buf,
		)
		if err != nil {
			logger.Printf("Backlog queue failed = %s", err)
		}

		req.Header.Set("Authorization", "Bearer "+ab.opt.ProjectKey)
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("User-Agent", userAgent)
		resp, err := ab.opt.HTTPClient.Do(req)
		if err != nil {
			logger.Printf("Backlog queue failed = %s", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode > 400 {
			logger.Printf("Backlog queue failed = %q", resp.Status)
		}
		buf.Reset()
	}
	ab.queues = nil
}
```

**Comment by kyrylo** [comment]
Hi Mattias! I pushed a PR, which hopefully fixes the problem: https://github.com/airbrake/gobrake/pull/352
Could you please take a look? I am not sure what you meant by "defensive" here.

**Comment by mattias-lundell** [comment]
@kyrylo excellent, looking forward to have this in a release!

**Comment by avinoamr** [comment]
@kyrylo any plans to add this fix to a future release version?

**Comment by kyrylo** [comment]
@avinoamr hey there! Unfortunately, I don’t work here anymore.
